spring.application.name=wms-backend
#puerto de producción
server.port=8080
#puerto de test
# server.port=9091
app.version=@project.version@

# ============================================================
# ⚙️ TOMCAT EMBEBIDO (rendimiento)
# ============================================================
server.tomcat.threads.max=400
server.tomcat.threads.min-spare=50
server.tomcat.max-connections=10000
server.tomcat.accept-count=1000
server.tomcat.connection-timeout=20s
server.tomcat.uri-encoding=UTF-8

# Compresión HTTP
server.compression.enabled=true
server.compression.min-response-size=1KB
server.compression.mime-types=text/html,text/xml,text/plain,application/json,application/javascript,application/xml

# Tamaño de headers (elige según tu versión de Spring Boot)
server.max-http-request-header-size=32KB 

# Hibernate
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.proc.param_null_passing=true

# Configuración para la base de datos wms_wd_general
spring.datasource.url=jdbc:sqlserver://wd-wms-prd.cyeyhpu1wzr0.us-east-2.rds.amazonaws.com:14331;databaseName=WmsWdGeneral;trustServerCertificate=true
spring.datasource.username=readermssql
spring.datasource.password=@e1aec2bc69bd4b1e
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Configuración del pool de conexiones (HikariCP)
spring.datasource.hikari.maximum-pool-size=40
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1500000
spring.datasource.hikari.auto-commit=true
spring.datasource.hikari.leak-detection-threshold=20000
spring.datasource.hikari.pool-name=WmsHikariCP

prn.path=C:\\Users\\e.agudelo\\Documents\\PruebasPrn\\TIGO-COLOMBIA-BOGOTA\\prns\\empaque



# server.ssl.key-store=classpath:keystore.p12
# server.ssl.key-store-password=W0d3n1t2021*
# server.ssl.key-store-type=PKCS12
# server.ssl.key-alias=tomcat
# logging.file.name=logs/app.log
# logging.level.root=INFO
# logging.level.org.springframework.web=DEBUG
# logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{50} - %msg%n