spring.application.name=wms-backend

# Hibernate
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Configuración para la base de datos wms_wd_general
spring.datasource.url=jdbc:sqlserver://wd-wms-prd.cyeyhpu1wzr0.us-east-2.rds.amazonaws.com:14331;databaseName=WmsWdGeneral;trustServerCertificate=true
spring.datasource.username=readermssql
spring.datasource.password=@e1aec2bc69bd4b1e
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Configuración para la base de datos de Legacy (Costa Rica)
cliente.datasource.url=jdbc:sqlserver://wd-wms-prd.cyeyhpu1wzr0.us-east-2.rds.amazonaws.com:14331;databaseName=WmsWdLegacyCostaRica;trustServerCertificate=true
cliente.datasource.username=readermssql
cliente.datasource.password=@e1aec2bc69bd4b1e
cliente.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# # Configuración para la base de datos WmsWdTigoColombiaBOG
# wms.datasource.tigo-bog.url=jdbc:sqlserver://wd-wms-prd.cyeyhpu1wzr0.us-east-2.rds.amazonaws.com:14331;databaseName=WmsWdTigoColombiaBOG;trustServerCertificate=true
# wms.datasource.tigo-bog.username=readermssql
# wms.datasource.tigo-bog.password=@e1aec2bc69bd4b1e
# wms.datasource.tigo-bog.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# # Configuración para la base de datos WmsWdTigoColombiaMED
# wms.datasource.tigo-med.url=jdbc:sqlserver://wd-wms-prd.cyeyhpu1wzr0.us-east-2.rds.amazonaws.com:14331;databaseName=WmsWdTigoColombiaMED;trustServerCertificate=true
# wms.datasource.tigo-med.username=readermssql
# wms.datasource.tigo-med.password=@e1aec2bc69bd4b1e
# wms.datasource.tigo-med.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# # Configuración para la base de datos WmsWdTelefonicaColombiaBOG
# wms.datasource.telefonica-bog.url=jdbc:sqlserver://wd-wms-prd.cyeyhpu1wzr0.us-east-2.rds.amazonaws.com:14331;databaseName=WmsWdTelefonicaColombiaBOG;trustServerCertificate=true
# wms.datasource.telefonica-bog.username=readermssql
# wms.datasource.telefonica-bog.password=@e1aec2bc69bd4b1e
# wms.datasource.telefonica-bog.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# # Configuración para la base de datos WmsWdTelefonicaColombiaRework
# wms.datasource.telefonica-rework.url=jdbc:sqlserver://wd-wms-prd.cyeyhpu1wzr0.us-east-2.rds.amazonaws.com:14331;databaseName=WmsWdTelefonicaColombiaRework;trustServerCertificate=true
# wms.datasource.telefonica-rework.username=readermssql
# wms.datasource.telefonica-rework.password=@e1aec2bc69bd4b1e
# wms.datasource.telefonica-rework.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver